config/routes.rb
Rails.application.routes.draw do

mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


 devise_for :users, controllers: {
   sessions: 'users/sessions'
 }
  get "userflights" => "user_flights#index"
  post "save_flight" => "user_flights#save_flight"

  root to: "home#index"

  resources :users do
    resources :user_flights do
    end
  end

  get "about-james" => "james#index"
  get "the-calculations" => "about#index"

  resources :flights
  resources :home
  resources :james
  resources :about

end

app/models/user_flight.rb
class UserFlight < ApplicationRecord
  belongs_to :user
end

app/controllers/user_flights_controller.rb
class UserFlightsController < ApplicationController
  def save_flight
    new_flight = current_user.user_flights.create(mpd: params[:mpd], price: params[:price], airlineNumber: params[:airlineNumber], airlineCarrier: params[:airlineCarrier], departureTime: params[:departureTime], arribalTime: params[:arribalTime], origin: params[:origin], destination: params[:destination])
  end

  def destroy
    savedflight = UserFlight.find(params[:id])
    savedflight.destroy
    redirect_to userflights_path
  end
end

app/views/user_flights/index.html.erb
<div class="saved-flights">
  <h1 class="my-header">Saved Flights</h1><hr> <h2>Welcome <%=current_user.email%></h2>
  <br>
  <% current_user.user_flights.each do |flight| %>

  <h3><%= link_to "",  user_user_flight_path(current_user, flight), :method => "delete", class: "btn-red glyphicon glyphicon-remove" %>  </h3>
    <h4>MPD: <%= flight.mpd %></h4>
    <h4>Price: <%= flight.price %></h4>
    <h4>Origin: <%= flight.origin %></h4>
    <h4>Destination: <%= flight.destination%></h4>
    <h4>Airline Carrier: <%= flight.airlineCarrier %></h4>
    <h4>Flight Number: <%= flight.airlineNumber %></h4>
    <h4>Departure Time: <%= flight.departureTime %></h4>
    <h4>Arrival Time: <%= flight.arribalTime %></h4>
  <br>
<% end %>
</div>