config/routes.rb
Rails.application.routes.draw do

mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


 devise_for :users, controllers: {
   sessions: 'users/sessions'
 }
  get "userflights" => "user_flights#index"
  post "save_flight" => "user_flights#save_flight"

  root to: "home#index"

  resources :users do
    resources :user_flights do
    end
  end

  get "about-james" => "james#index"
  get "the-calculations" => "about#index"

  resources :flights
  resources :home
  resources :james
  resources :about

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoogleFlights</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="/assets/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>

  <body>
    <div class="row nav-left" >
      <div class="col-md-3 nav-left">
        <div class="nav-bar" id="first-nav">
          <h1> <%= link_to "Search Flights",  '/' %></h1>
        </div>
        <div class="nav-bar" id="second-nav">
          <h1> <%= link_to "The Algorithm",  '/the-calculations' %></h1>
        </div>
        <div class="nav-bar" id="third-nav">
          <h1><%= link_to "Your Saved Flights",  userflights_path %></h1>
        </div>
        <div class="nav-bar" id="fourth-nav">
          <h1> <%= link_to "About James",  '/about-james' %></h1>
        </div>
      </div>
      <div class="col-md-9 nav-body">
        <h3 class="my-sign"> <%= link_to 'Sign Out',  destroy_user_session_path, :method => "delete" if user_signed_in? %> </h3>
        <h3 class="my-sign">  <%= link_to "Sign In |", new_user_session_path if !user_signed_in? %>  <%= link_to "Sign Up", new_user_registration_path if !user_signed_in? %></h3>
        <h3 class="my-sign"></h3>
        <h3 class="my-sign"><%= yield %>
      </div>
    </div>
  </body>
</html>